pipeline {
    agent {
    node{
	 label 'docker'
	}
    }
    environment {
    dockerhub=credentials('docker_hub')
    }
    stages{
        stage('Docker Build') {
            steps {
                sh 'cd webapp && docker build -t divyadoc29/frontend .'
             }
          }
        stage('Docker Login') {
            steps {
                sh 'echo $dockerhub_PSW | docker login -u $dockerhub_USR --password-stdin'
            }
          }
        stage('Docker Push') {
            steps {
                sh 'docker push divyadoc29/frontend'
            }
          }
        stage('Remove old images') {
            steps {
                sh 'docker rmi -f divyadoc29/frontend'
              }
          }
	stage('Remove old container') {
            steps {
                sh 'docker container rm web -f'
              }
          }
        stage('Docker run'){
            steps{
                sh 'docker container run -dt --name web -p 80:80 divyadoc29/frontend'
            }
         }
	}
}
